title: Researcher
url: "https://johndef64.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/johndef64"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index" #"/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Publications"
   link: "publications"
 - name: "Contact"
   link: "contact"
